apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twitter-tracker
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: twitter-tracker
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: twitter-tracker
        image: projectepic/twitter-tracker:{{version}}
        imagePullPolicy: Always
        resources:
          limits:
           memory: 50Mi
           cpu: "50m"
          requests:
           memory: 50Mi
           cpu: "50m"


        env:
            - name: ACCESS_TOKEN
              value: {{a_token}}
            - name: ACCESS_TOKEN_SECRET
              value: {{a_token_secret}}
            - name: CONSUMER_KEY
              value: {{c_key}}
            - name: CONSUMER_SECRET
              value: {{c_secret}}
            - name: TOKENS
              value: "{{queries}}"
            - name: KAFKA_SERVERS
              value: {{kafka-servers}}

